spring.application.name=VetCare

spring.datasource.url=jdbc:mysql://localhost:3306/vet_care?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# para criação das tabelas no banco, atualização automática
# SQL DDL data definition language
spring.jpa.hibernate.ddl-auto=update
# mostra código sql utilido
spring.jpa.show-sql=true
