@baseUrl = http://localhost:8080

### Criar um novo Tutor1
POST http://localhost:8080/api/tutores
Content-Type: application/json

{
  "nome": "Mauricio",
  "cpf": "555444666-44",
  "rg": "9564256",
  "email": "mauricio@email.com",
  "telefone": "48 99999 9999",
  "endereco": {
    "cep": "88000-000",
    "logradouro": "Rua Jose Beiro",
    "numero": "521",
    "complemento": "Apto 101",
    "cidade": "Florianópolis",
    "estado": "Santa Catarina",
    "uf": "SC"
  }
}


### Criar um novo Tutor2
POST http://localhost:8080/api/tutores
Content-Type: application/json

{
  "nome": "Adriana",
  "cpf": "333444666-44",
  "rg": "5554256",
  "email": "adriana@email.com",
  "telefone": "48 98888 9999",
  "endereco": {
    "cep": "88000-000",
    "logradouro": "Rua Jose Beiro",
    "numero": "521",
    "complemento": "Apto 101",
    "cidade": "Florianópolis",
    "estado": "Santa Catarina",
    "uf": "SC"
  }
}


### Criar um novo Tutor3
POST http://localhost:8080/api/tutores
Content-Type: application/json

{
  "nome": "Roberto",
  "cpf": "333555666-44",
  "rg": "7774256",
  "email": "roberto@email.com",
  "telefone": "48 97777 9999",
  "endereco": {
    "cep": "88000-555",
    "logradouro": "Rua Santos Saraiva",
    "numero": "898",
    "complemento": "",
    "cidade": "Florianópolis",
    "estado": "Santa Catarina",
    "uf": "SC"
  }
}


### Criar um novo Tutor4
POST http://localhost:8080/api/tutores
Content-Type: application/json

{
  "nome": "Fernanda",
  "cpf": "777444666-44",
  "rg": "6665876",
  "email": "fernanda@email.com",
  "telefone": "48 96666 9999",
  "endereco": {
    "cep": "88000-888",
    "logradouro": "Av. Rio Branco",
    "numero": "333",
    "complemento": "SL 1001",
    "cidade": "Florianópolis",
    "estado": "Santa Catarina",
    "uf": "SC"
  }
}


### Buscar Tutor por ID
GET http://localhost:8080/api/tutores/1
Accept: application/json

### Listar tutores não paginado
GET {{baseUrl}}/api/tutores

### Listar tutores paginado
GET {{baseUrl}}/api/tutores?page=0&size=5&sort=nome,asc

### Atualizar Tutor parcial
PATCH {{baseUrl}}/api/tutores/3
Content-Type: application/json

{
    "nome":"Roberto Carlos",
    "endereco":{
    "cep": "99999-999"
  }
}

### Atualizar Tutor completo
PUT {{baseUrl}}/api/tutores/3
Content-Type: application/json

{
  "nome": "Roberto Pirata",
  "cpf": "333555666-44",
  "rg": "7774256",
  "email": "robertopirata@email.com",
  "telefone": "48 97777 9999",
  "endereco": {
    "cep": "88000-555",
    "logradouro": "Rua dos Piratas",
    "numero": "898",
    "complemento": "Barco Pirata",
    "cidade": "Florianópolis",
    "estado": "Santa Catarina",
    "uf": "SC"
  }
}

### Deletar Tutor por ID
DELETE {{baseUrl}}/api/tutores/4